/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Sun Jun 16 16:05:41 2024.
 */

#include <string.h>

#include "nlg5_database_can.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int nlg5_database_can_nlg5_diag_tx_pack(
    uint8_t *dst_p,
    const struct nlg5_database_can_nlg5_diag_tx_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u64(src_p->lad_d_param_rp, 56u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->lad_d_param_rp, 48u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->lad_d_param_rp, 40u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->lad_d_param_rp, 32u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->lad_d_param_rp, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->lad_d_param_rp, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->lad_d_param_rp, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u64(src_p->lad_d_param_rp, 0u, 0xffu);

    return (8);
}

int nlg5_database_can_nlg5_diag_tx_unpack(
    struct nlg5_database_can_nlg5_diag_tx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lad_d_param_rp = unpack_left_shift_u64(src_p[0], 56u, 0xffu);
    dst_p->lad_d_param_rp |= unpack_left_shift_u64(src_p[1], 48u, 0xffu);
    dst_p->lad_d_param_rp |= unpack_left_shift_u64(src_p[2], 40u, 0xffu);
    dst_p->lad_d_param_rp |= unpack_left_shift_u64(src_p[3], 32u, 0xffu);
    dst_p->lad_d_param_rp |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
    dst_p->lad_d_param_rp |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->lad_d_param_rp |= unpack_left_shift_u64(src_p[6], 8u, 0xffu);
    dst_p->lad_d_param_rp |= unpack_right_shift_u64(src_p[7], 0u, 0xffu);

    return (0);
}

uint64_t nlg5_database_can_nlg5_diag_tx_lad_d_param_rp_encode(double value)
{
    return (uint64_t)(value);
}

double nlg5_database_can_nlg5_diag_tx_lad_d_param_rp_decode(uint64_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_diag_tx_lad_d_param_rp_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int nlg5_database_can_nlg5_diag_rx_pack(
    uint8_t *dst_p,
    const struct nlg5_database_can_nlg5_diag_rx_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u64(src_p->lad_d_param_rq, 56u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->lad_d_param_rq, 48u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->lad_d_param_rq, 40u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->lad_d_param_rq, 32u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->lad_d_param_rq, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->lad_d_param_rq, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->lad_d_param_rq, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u64(src_p->lad_d_param_rq, 0u, 0xffu);

    return (8);
}

int nlg5_database_can_nlg5_diag_rx_unpack(
    struct nlg5_database_can_nlg5_diag_rx_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lad_d_param_rq = unpack_left_shift_u64(src_p[0], 56u, 0xffu);
    dst_p->lad_d_param_rq |= unpack_left_shift_u64(src_p[1], 48u, 0xffu);
    dst_p->lad_d_param_rq |= unpack_left_shift_u64(src_p[2], 40u, 0xffu);
    dst_p->lad_d_param_rq |= unpack_left_shift_u64(src_p[3], 32u, 0xffu);
    dst_p->lad_d_param_rq |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
    dst_p->lad_d_param_rq |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->lad_d_param_rq |= unpack_left_shift_u64(src_p[6], 8u, 0xffu);
    dst_p->lad_d_param_rq |= unpack_right_shift_u64(src_p[7], 0u, 0xffu);

    return (0);
}

uint64_t nlg5_database_can_nlg5_diag_rx_lad_d_param_rq_encode(double value)
{
    return (uint64_t)(value);
}

double nlg5_database_can_nlg5_diag_rx_lad_d_param_rq_decode(uint64_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_diag_rx_lad_d_param_rq_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int nlg5_database_can_nlg5_err_pack(
    uint8_t *dst_p,
    const struct nlg5_database_can_nlg5_err_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_e_oov, 7u, 0x80u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_e_mov_ii, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_e_mov_i, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_e_sc, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_e_p_om, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_e_p_mv, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_e_of, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_e_mf, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_e_b_p, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_e_t_c, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_e_t_pow, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_e_t_dio, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_e_t_tr, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_e_t_ext1, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_e_t_ext2, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_e_t_ext3, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_e_f_crc, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_e_nv_crc, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_e_es_crc, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_e_ep_crc, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_e_wdt, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_e_init, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_e_c_to, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_e_c_off, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->nlg5_e_c_tx, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u8(src_p->nlg5_e_c_rx, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->nlg5_e_sdt_bt, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->nlg5_e_sdt_bv, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->nlg5_e_sdt_ah, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->nlg5_e_sdt_ct, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->nlg5_w_pl_mv, 7u, 0x80u);
    dst_p[4] |= pack_left_shift_u8(src_p->nlg5_w_pl_bv, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->nlg5_w_pl_it, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->nlg5_w_c_vor, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->nlg5_w_cm_na, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->nlg5_w_od, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->nlg5_w_sc_m, 0u, 0x01u);

    return (5);
}

int nlg5_database_can_nlg5_err_unpack(
    struct nlg5_database_can_nlg5_err_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->nlg5_e_oov = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->nlg5_e_mov_ii = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->nlg5_e_mov_i = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->nlg5_e_sc = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->nlg5_e_p_om = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->nlg5_e_p_mv = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->nlg5_e_of = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->nlg5_e_mf = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->nlg5_e_b_p = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->nlg5_e_t_c = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->nlg5_e_t_pow = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->nlg5_e_t_dio = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->nlg5_e_t_tr = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->nlg5_e_t_ext1 = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->nlg5_e_t_ext2 = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->nlg5_e_t_ext3 = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->nlg5_e_f_crc = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->nlg5_e_nv_crc = unpack_right_shift_u8(src_p[2], 6u, 0x40u);
    dst_p->nlg5_e_es_crc = unpack_right_shift_u8(src_p[2], 5u, 0x20u);
    dst_p->nlg5_e_ep_crc = unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->nlg5_e_wdt = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->nlg5_e_init = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->nlg5_e_c_to = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->nlg5_e_c_off = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->nlg5_e_c_tx = unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->nlg5_e_c_rx = unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->nlg5_e_sdt_bt = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->nlg5_e_sdt_bv = unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->nlg5_e_sdt_ah = unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->nlg5_e_sdt_ct = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->nlg5_w_pl_mv = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->nlg5_w_pl_bv = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->nlg5_w_pl_it = unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->nlg5_w_c_vor = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->nlg5_w_cm_na = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->nlg5_w_od = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->nlg5_w_sc_m = unpack_right_shift_u8(src_p[4], 0u, 0x01u);

    return (0);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_oov_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_oov_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_oov_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_mov_ii_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_mov_ii_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_mov_ii_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_mov_i_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_mov_i_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_mov_i_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_sc_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_sc_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_sc_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_p_om_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_p_om_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_p_om_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_p_mv_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_p_mv_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_p_mv_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_of_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_of_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_of_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_mf_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_mf_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_mf_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_b_p_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_b_p_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_b_p_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_t_c_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_t_c_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_t_c_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_t_pow_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_t_pow_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_t_pow_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_t_dio_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_t_dio_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_t_dio_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_t_tr_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_t_tr_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_t_tr_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_t_ext1_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_t_ext1_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_t_ext1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_t_ext2_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_t_ext2_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_t_ext2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_t_ext3_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_t_ext3_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_t_ext3_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_f_crc_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_f_crc_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_f_crc_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_nv_crc_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_nv_crc_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_nv_crc_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_es_crc_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_es_crc_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_es_crc_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_ep_crc_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_ep_crc_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_ep_crc_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_wdt_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_wdt_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_wdt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_init_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_init_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_init_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_c_to_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_c_to_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_c_to_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_c_off_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_c_off_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_c_off_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_c_tx_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_c_tx_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_c_tx_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_c_rx_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_c_rx_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_c_rx_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_sdt_bt_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_sdt_bt_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_sdt_bt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_sdt_bv_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_sdt_bv_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_sdt_bv_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_sdt_ah_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_sdt_ah_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_sdt_ah_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_e_sdt_ct_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_e_sdt_ct_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_e_sdt_ct_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_w_pl_mv_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_w_pl_mv_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_w_pl_mv_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_w_pl_bv_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_w_pl_bv_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_w_pl_bv_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_w_pl_it_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_w_pl_it_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_w_pl_it_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_w_c_vor_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_w_c_vor_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_w_c_vor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_w_cm_na_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_w_cm_na_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_w_cm_na_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_w_od_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_w_od_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_w_od_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_err_nlg5_w_sc_m_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_err_nlg5_w_sc_m_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_err_nlg5_w_sc_m_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int nlg5_database_can_nlg5_temp_pack(
    uint8_t *dst_p,
    const struct nlg5_database_can_nlg5_temp_t *src_p,
    size_t size)
{
    uint16_t nlg5_p_tmp;
    uint16_t nlg5_temp_ext2;
    uint16_t nlg5_tmp_ext1;
    uint16_t nlg5_tmp_ext3;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    nlg5_p_tmp = (uint16_t)src_p->nlg5_p_tmp;
    dst_p[0] |= pack_right_shift_u16(nlg5_p_tmp, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(nlg5_p_tmp, 0u, 0xffu);
    nlg5_tmp_ext1 = (uint16_t)src_p->nlg5_tmp_ext1;
    dst_p[2] |= pack_right_shift_u16(nlg5_tmp_ext1, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(nlg5_tmp_ext1, 0u, 0xffu);
    nlg5_temp_ext2 = (uint16_t)src_p->nlg5_temp_ext2;
    dst_p[4] |= pack_right_shift_u16(nlg5_temp_ext2, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(nlg5_temp_ext2, 0u, 0xffu);
    nlg5_tmp_ext3 = (uint16_t)src_p->nlg5_tmp_ext3;
    dst_p[6] |= pack_right_shift_u16(nlg5_tmp_ext3, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(nlg5_tmp_ext3, 0u, 0xffu);

    return (8);
}

int nlg5_database_can_nlg5_temp_unpack(
    struct nlg5_database_can_nlg5_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t nlg5_p_tmp;
    uint16_t nlg5_temp_ext2;
    uint16_t nlg5_tmp_ext1;
    uint16_t nlg5_tmp_ext3;

    if (size < 8u) {
        return (-EINVAL);
    }

    nlg5_p_tmp = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    nlg5_p_tmp |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->nlg5_p_tmp = (int16_t)nlg5_p_tmp;
    nlg5_tmp_ext1 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    nlg5_tmp_ext1 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->nlg5_tmp_ext1 = (int16_t)nlg5_tmp_ext1;
    nlg5_temp_ext2 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    nlg5_temp_ext2 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->nlg5_temp_ext2 = (int16_t)nlg5_temp_ext2;
    nlg5_tmp_ext3 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    nlg5_tmp_ext3 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->nlg5_tmp_ext3 = (int16_t)nlg5_tmp_ext3;

    return (0);
}

int16_t nlg5_database_can_nlg5_temp_nlg5_p_tmp_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double nlg5_database_can_nlg5_temp_nlg5_p_tmp_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_temp_nlg5_p_tmp_is_in_range(int16_t value)
{
    return ((value >= -400) && (value <= 3000));
}

int16_t nlg5_database_can_nlg5_temp_nlg5_tmp_ext1_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double nlg5_database_can_nlg5_temp_nlg5_tmp_ext1_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_temp_nlg5_tmp_ext1_is_in_range(int16_t value)
{
    return ((value >= -400) && (value <= 3000));
}

int16_t nlg5_database_can_nlg5_temp_nlg5_temp_ext2_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double nlg5_database_can_nlg5_temp_nlg5_temp_ext2_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_temp_nlg5_temp_ext2_is_in_range(int16_t value)
{
    return ((value >= -400) && (value <= 3000));
}

int16_t nlg5_database_can_nlg5_temp_nlg5_tmp_ext3_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double nlg5_database_can_nlg5_temp_nlg5_tmp_ext3_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_temp_nlg5_tmp_ext3_is_in_range(int16_t value)
{
    return ((value >= -400) && (value <= 3000));
}

int nlg5_database_can_nlg5_act_ii_pack(
    uint8_t *dst_p,
    const struct nlg5_database_can_nlg5_act_ii_t *src_p,
    size_t size)
{
    uint16_t nlg5_ahc_ext;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->nlg5_s_mc_m_cp, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->nlg5_s_mc_m_cp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_s_mc_m_pi, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->nlg5_abv, 0u, 0xffu);
    nlg5_ahc_ext = (uint16_t)src_p->nlg5_ahc_ext;
    dst_p[4] |= pack_right_shift_u16(nlg5_ahc_ext, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(nlg5_ahc_ext, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->nlg5_oc_bo, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->nlg5_oc_bo, 0u, 0xffu);

    return (8);
}

int nlg5_database_can_nlg5_act_ii_unpack(
    struct nlg5_database_can_nlg5_act_ii_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t nlg5_ahc_ext;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->nlg5_s_mc_m_cp = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->nlg5_s_mc_m_cp |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->nlg5_s_mc_m_pi = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->nlg5_abv = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    nlg5_ahc_ext = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    nlg5_ahc_ext |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->nlg5_ahc_ext = (int16_t)nlg5_ahc_ext;
    dst_p->nlg5_oc_bo = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->nlg5_oc_bo |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint16_t nlg5_database_can_nlg5_act_ii_nlg5_s_mc_m_cp_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double nlg5_database_can_nlg5_act_ii_nlg5_s_mc_m_cp_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_act_ii_nlg5_s_mc_m_cp_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint8_t nlg5_database_can_nlg5_act_ii_nlg5_s_mc_m_pi_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double nlg5_database_can_nlg5_act_ii_nlg5_s_mc_m_pi_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_act_ii_nlg5_s_mc_m_pi_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

uint8_t nlg5_database_can_nlg5_act_ii_nlg5_abv_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double nlg5_database_can_nlg5_act_ii_nlg5_abv_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_act_ii_nlg5_abv_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

int16_t nlg5_database_can_nlg5_act_ii_nlg5_ahc_ext_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double nlg5_database_can_nlg5_act_ii_nlg5_ahc_ext_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool nlg5_database_can_nlg5_act_ii_nlg5_ahc_ext_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t nlg5_database_can_nlg5_act_ii_nlg5_oc_bo_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double nlg5_database_can_nlg5_act_ii_nlg5_oc_bo_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool nlg5_database_can_nlg5_act_ii_nlg5_oc_bo_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

int nlg5_database_can_nlg5_act_i_pack(
    uint8_t *dst_p,
    const struct nlg5_database_can_nlg5_act_i_t *src_p,
    size_t size)
{
    uint16_t nlg5_oc_act;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->nlg5_mc_act, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->nlg5_mc_act, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->nlg5_mv_act, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->nlg5_mv_act, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->nlg5_ov_act, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->nlg5_ov_act, 0u, 0xffu);
    nlg5_oc_act = (uint16_t)src_p->nlg5_oc_act;
    dst_p[6] |= pack_right_shift_u16(nlg5_oc_act, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(nlg5_oc_act, 0u, 0xffu);

    return (8);
}

int nlg5_database_can_nlg5_act_i_unpack(
    struct nlg5_database_can_nlg5_act_i_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t nlg5_oc_act;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->nlg5_mc_act = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->nlg5_mc_act |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->nlg5_mv_act = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->nlg5_mv_act |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->nlg5_ov_act = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->nlg5_ov_act |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    nlg5_oc_act = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    nlg5_oc_act |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->nlg5_oc_act = (int16_t)nlg5_oc_act;

    return (0);
}

uint16_t nlg5_database_can_nlg5_act_i_nlg5_mc_act_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double nlg5_database_can_nlg5_act_i_nlg5_mc_act_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool nlg5_database_can_nlg5_act_i_nlg5_mc_act_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t nlg5_database_can_nlg5_act_i_nlg5_mv_act_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double nlg5_database_can_nlg5_act_i_nlg5_mv_act_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_act_i_nlg5_mv_act_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

uint16_t nlg5_database_can_nlg5_act_i_nlg5_ov_act_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double nlg5_database_can_nlg5_act_i_nlg5_ov_act_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_act_i_nlg5_ov_act_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

int16_t nlg5_database_can_nlg5_act_i_nlg5_oc_act_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double nlg5_database_can_nlg5_act_i_nlg5_oc_act_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool nlg5_database_can_nlg5_act_i_nlg5_oc_act_is_in_range(int16_t value)
{
    return ((value >= 0) && (value <= 15000));
}

int nlg5_database_can_nlg5_st_pack(
    uint8_t *dst_p,
    const struct nlg5_database_can_nlg5_st_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_s_he, 7u, 0x80u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_s_err, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_s_war, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_s_fan, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_s_eum, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_s_um_i, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_s_um_ii, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_s_cp_dt, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_s_bpd_i, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_s_bpd_ii, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_s_l_ov, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_s_l_oc, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_s_l_mc, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_s_l_pi, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_s_l_cp, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->nlg5_s_l_pmax, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_s_l_mc_max, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_s_l_oc_max, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_s_l_mo_max, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_s_l_t_cprim, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_s_l_t_pow, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_s_l_t_dio, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_s_l_t_tr, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->nlg5_s_l_t_batt, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->nlg5_s_aac, 0u, 0x01u);

    return (4);
}

int nlg5_database_can_nlg5_st_unpack(
    struct nlg5_database_can_nlg5_st_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->nlg5_s_he = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->nlg5_s_err = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->nlg5_s_war = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->nlg5_s_fan = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->nlg5_s_eum = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->nlg5_s_um_i = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->nlg5_s_um_ii = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->nlg5_s_cp_dt = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->nlg5_s_bpd_i = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->nlg5_s_bpd_ii = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->nlg5_s_l_ov = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->nlg5_s_l_oc = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->nlg5_s_l_mc = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->nlg5_s_l_pi = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->nlg5_s_l_cp = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->nlg5_s_l_pmax = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->nlg5_s_l_mc_max = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->nlg5_s_l_oc_max = unpack_right_shift_u8(src_p[2], 6u, 0x40u);
    dst_p->nlg5_s_l_mo_max = unpack_right_shift_u8(src_p[2], 5u, 0x20u);
    dst_p->nlg5_s_l_t_cprim = unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->nlg5_s_l_t_pow = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->nlg5_s_l_t_dio = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->nlg5_s_l_t_tr = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->nlg5_s_l_t_batt = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->nlg5_s_aac = unpack_right_shift_u8(src_p[3], 0u, 0x01u);

    return (0);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_he_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_he_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_he_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_err_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_err_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_err_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_war_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_war_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_war_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_fan_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_fan_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_fan_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_eum_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_eum_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_eum_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_um_i_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_um_i_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_um_i_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_um_ii_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_um_ii_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_um_ii_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_cp_dt_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_cp_dt_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_cp_dt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_bpd_i_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_bpd_i_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_bpd_i_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_bpd_ii_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_bpd_ii_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_bpd_ii_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_ov_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_ov_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_ov_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_oc_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_oc_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_oc_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_mc_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_mc_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_mc_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_pi_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_pi_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_pi_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_cp_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_cp_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_cp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_pmax_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_pmax_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_pmax_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_mc_max_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_mc_max_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_mc_max_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_oc_max_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_oc_max_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_oc_max_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_mo_max_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_mo_max_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_mo_max_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_t_cprim_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_t_cprim_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_t_cprim_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_t_pow_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_t_pow_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_t_pow_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_t_dio_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_t_dio_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_t_dio_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_t_tr_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_t_tr_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_t_tr_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_l_t_batt_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_l_t_batt_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_l_t_batt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_st_nlg5_s_aac_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_st_nlg5_s_aac_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_st_nlg5_s_aac_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int nlg5_database_can_nlg5_ctl_pack(
    uint8_t *dst_p,
    const struct nlg5_database_can_nlg5_ctl_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_c_c_en, 7u, 0x80u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_c_c_el, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_c_cp_v, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->nlg5_c_mr, 4u, 0x10u);
    dst_p[1] |= pack_right_shift_u16(src_p->nlg5_mc_max, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->nlg5_mc_max, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->nlg5_ov_com, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->nlg5_ov_com, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->nlg5_oc_com, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->nlg5_oc_com, 0u, 0xffu);

    return (7);
}

int nlg5_database_can_nlg5_ctl_unpack(
    struct nlg5_database_can_nlg5_ctl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->nlg5_c_c_en = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->nlg5_c_c_el = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->nlg5_c_cp_v = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->nlg5_c_mr = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->nlg5_mc_max = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->nlg5_mc_max |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->nlg5_ov_com = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->nlg5_ov_com |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->nlg5_oc_com = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->nlg5_oc_com |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);

    return (0);
}

uint8_t nlg5_database_can_nlg5_ctl_nlg5_c_c_en_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_ctl_nlg5_c_c_en_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_ctl_nlg5_c_c_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_ctl_nlg5_c_c_el_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_ctl_nlg5_c_c_el_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_ctl_nlg5_c_c_el_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_ctl_nlg5_c_cp_v_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_ctl_nlg5_c_cp_v_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_ctl_nlg5_c_cp_v_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t nlg5_database_can_nlg5_ctl_nlg5_c_mr_encode(double value)
{
    return (uint8_t)(value);
}

double nlg5_database_can_nlg5_ctl_nlg5_c_mr_decode(uint8_t value)
{
    return ((double)value);
}

bool nlg5_database_can_nlg5_ctl_nlg5_c_mr_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t nlg5_database_can_nlg5_ctl_nlg5_mc_max_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double nlg5_database_can_nlg5_ctl_nlg5_mc_max_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_ctl_nlg5_mc_max_is_in_range(uint16_t value)
{
    return (value <= 500u);
}

uint16_t nlg5_database_can_nlg5_ctl_nlg5_ov_com_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double nlg5_database_can_nlg5_ctl_nlg5_ov_com_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_ctl_nlg5_ov_com_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

uint16_t nlg5_database_can_nlg5_ctl_nlg5_oc_com_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double nlg5_database_can_nlg5_ctl_nlg5_oc_com_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool nlg5_database_can_nlg5_ctl_nlg5_oc_com_is_in_range(uint16_t value)
{
    return (value <= 1500u);
}
